services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: cineverse
      POSTGRES_USER: cineverse
      POSTGRES_PASSWORD: cineverse
    ports:
      - "5432:5432"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  frontend:
    build:
      context: ../Frontend
    ports:
      - "3000:80"
    depends_on:
      - rabbitmq
      - redis
